wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709807478.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.11.3
      5: 0.16.4
      6: 4.38.1
      8:
      - 3
      - 5
      13: windows-amd64
